# Generated by Django 4.0.5 on 2023-03-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisrmutiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
