# Generated by Django 4.0.5 on 2023-03-09 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bisrmutiapp', '0005_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_style', models.CharField(max_length=250)),
                ('car_size', models.CharField(max_length=250)),
                ('car_price', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pep1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bisrmutiapp.car_brand')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bisrmutiapp.orders')),
            ],
            options={
                'unique_together': {('order_id', 'car_brand')},
            },
        ),
    ]
