# Generated by Django 4.0.5 on 2023-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisrmutiapp', '0006_car_brand_remove_customuser_username_customuser_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
