# Generated by Django 4.0.5 on 2023-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisrmutiapp', '0007_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_brand',
            name='car_yeehaw',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
